### PR TITLE
Write on read

### PR DESCRIPTION
**Pull request by jensens**
see plone/buildout.coredev#150 merge together with other

### CODE REVIEW

**Comment by jensens** [comment]
zero diff :) looks like this was merged in some way already.

**Comment by gforcada** [comment]
@jensens because it was merged but then tests failed so I reverted them.

**Comment by gforcada** [comment]
There's some hiccup on github UI right now, I fixed 2.1.x branch to **not** have the fix but it's still shown here ... maybe it needs some time...

**Comment by gforcada** [comment]
Ok, fixed it with a silly change :-)

**Pull request merged**
