### PR TITLE
PloneTestCase removal

### PR DESCRIPTION
**Pull request by tisto**

### CODE REVIEW

**Comment by tomgross** [comment]
Should be ok now

**Comment by gforcada** [comment]
Let's give it a try then: http://jenkins.plone.org/job/pull-request/67

**Comment by tisto** [comment]
Looks like the master branch needs to be merged into the tomgross-ptc branch to make the tests pass.

**Comment by tisto** [comment]
Will look into it...

**Comment by tisto** [comment]
Build is green, will merge: http://jenkins.plone.org/view/PLIPs/job/plip-ptc/56/

**Pull request merged**
