### PR TITLE
removed change portal events

### PR DESCRIPTION
**Pull request by kakshay21**
https://github.com/plone/Products.CMFPlone/issues/1975

### CODE REVIEW

**Comment by gforcada** [comment]
@jensens @mauritsvanrees do we need a deprecation notice on that? Or is sooo old already that it does not hurt?

**Comment by gforcada** [comment]
@kakshay21 Jenkins failed because you test only this pull request alone. As you are making related changes on different repositories, you need to put **all** pull requests on the same jenkins job, one per line.

Keep going, we are getting closer to merge! 👍

**Comment by mauritsvanrees** [comment]
It's probably fine to not use a deprecation warning.

It *could* be done, using the [Plone Deprecation Guide](https://docs.plone.org/develop/styleguide/deprecation.html#deprecating-methods-and-properties). But it may lead to unclear errors. I tried changing it to this to see what would happen:

```
from zope.deprecation import deprecated
ChangeEvents = 'Change portal events'
ChangeEvents = deprecated(
    ChangeEvents,
    'The ChangeEvents ("Change portal events") permission is gone. '
    'Please use another permission or create your own.'
)
setDefaultRoles(ChangeEvents, ('Manager', 'Site Administrator', 'Owner',))
```

The result is that `ChangeEvents` is `None`, which leads to this error on startup:

```
2017-04-11 15:44:16 ERROR Application Could not import Products.ATContentTypes
Traceback (most recent call last):
  File "/Users/maurits/shared-eggs/cp27m/Zope2-2.13.26-py2.7.egg/OFS/Application.py", line 606, in import_product
    product=__import__(pname, global_dict, global_dict, silly)
  File "/Users/maurits/community/plone-coredev/5.1/src/Products.ATContentTypes/Products/ATContentTypes/__init__.py", line 33, in <module>
    import Products.ATContentTypes.content  # noqa
  File "/Users/maurits/community/plone-coredev/5.1/src/Products.ATContentTypes/Products/ATContentTypes/content/__init__.py", line 2, in <module>
    import Products.ATContentTypes.content.link  # noqa
  File "/Users/maurits/community/plone-coredev/5.1/src/Products.ATContentTypes/Products/ATContentTypes/content/link.py", line 8, in <module>
    from Products.ATContentTypes.content.base import ATCTContent
  File "/Users/maurits/community/plone-coredev/5.1/src/Products.ATContentTypes/Products/ATContentTypes/content/base.py", line 15, in <module>
    from Products.ATContentTypes.lib.constraintypes import ConstrainTypesMixin
  File "/Users/maurits/community/plone-coredev/5.1/src/Products.ATContentTypes/Products/ATContentTypes/lib/constraintypes.py", line 14, in <module>
    from Products.ATContentTypes import permission as ATCTPermissions
  File "/Users/maurits/community/plone-coredev/5.1/src/Products.ATContentTypes/Products/ATContentTypes/permission.py", line 32, in <module>
    setDefaultRoles(ChangeEvents, ('Manager', 'Site Administrator', 'Owner',))
  File "/Users/maurits/shared-eggs/cp27m/Products.CMFCore-2.2.11-py2.7.egg/Products/CMFCore/permissions.py", line 67, in setDefaultRoles
    addPermission(permission, roles)
  File "/Users/maurits/shared-eggs/cp27m/AccessControl-3.0.13-py2.7-macosx-10.12-x86_64.egg/AccessControl/Permission.py", line 155, in addPermission
    mangled = pname(perm) # get mangled permission name
  File "/Users/maurits/shared-eggs/cp27m/AccessControl-3.0.13-py2.7-macosx-10.12-x86_64.egg/AccessControl/Permission.py", line 26, in pname
    return '_'+translate(name, name_trans) + "_Permission"
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/string.py", line 500, in translate
    return s.translate(table + s[:0])
AttributeError: 'NoneType' object has no attribute 'translate'
```

Of course we don't need to call `setDefaultRoles` anymore, but the point is that the error is less clear than an `ImportError` would be.

So: it is better to not use a deprecation warning here.

**Comment by gforcada** [comment]
Cool then, @kakshay21 let's try to fix the Jenkins error and then we would be good to go for merging!

**Comment by kakshay21** [comment]
I tried to make all my PR in one build and that one failed too. @gforcada

**Comment by gforcada** [comment]
@kakshay21 I see that you already started another job with even more pull requests... sorry about that 😞 there seems to be a lot of packages depending on each other...

**Comment by kakshay21** [comment]
Only one error left!! @gforcada

**Comment by gforcada** [comment]
Superseeded on #47

**Pull request closed without merging**
