### PR TITLE
Update permission.py

### PR DESCRIPTION
**Pull request by kakshay21**
removed Change portal events  as it's usage was removed in svn revision r104169
issues mentioned: Remove unused permission "Change portal events". plone/Products.CMFPlone#1975
@jensens

### CODE REVIEW

**Comment by jensens** [comment]
Sorry for being late, busy time here. 

1. A changelog entry is missing
2. this has to be merged together with other changes/removals. see my comment at https://github.com/plone/Products.CMFPlone/issues/1975#issue-216130183

For some reasons Jenkins was not triggered, lets see if this can be done manual.

**Comment by kakshay21** [comment]
Sorry about that. I was not aware of this.
@gforcada @mister-roboto

**Comment by gforcada** [comment]
No need to be sorry 😃 signing the contributors agreement would be a first step towards plone contributions.

And add a changelog entry to CHANGES.est as well.

Thanks for contributing to Plone!

**Comment by gforcada** [comment]
@kakshay21 why did you close? the changes were good, you only had to sign the CLA, which seems you already did, congrats! Welcome to Plone!

Whenever you want, please re-create it so we can merge it!

**Comment by kakshay21** [comment]
I've created another PR because in this PR I made changes directly in the master which is not recommended according to plone documentation for new contributors.
so I made another PR with separate branch.

**Comment by gforcada** [comment]
Oh I see. The docs probably meant if you were making the commits on this repository itself (i.e. github.com/PLONE/Products.ATContentTypes) but if you are making the changes on your own fork, then it does not really matter that much.

It matters if you are planning on using that master branch for other things (other pull requests, etc).

Anyway the code is not lost, that's the important thing.

Thanks again for taking the time to contribute to Plone!

**Pull request closed without merging**
