### PR TITLE
Removed ``Products.ATContentTypes.interface`` which was left only for…

### PR DESCRIPTION
**Pull request by thet**
… BBB compatibility.

# Pull requests fixing imports:
## Testing for 4.3, 5.0, 5.1: http://jenkins.plone.org/job/pull-request-4.3/532/
- [x] https://github.com/plone/archetypes.schemaextender/pull/3
- [x] https://github.com/plone/Products.contentmigration/pull/13
- [x] https://github.com/plone/Products.LinguaPlone/pull/23
- [x] https://github.com/plone/archetypes.referencebrowserwidget/pull/34
## Testing for 5.0, 5.1: http://jenkins.plone.org/job/pull-request-5.0/1819/
- [x] https://github.com/plone/plone.app.folder/pull/13
- [x] https://github.com/plone/plone.app.contenttypes/pull/390
## Testing for 5.1 only: http://jenkins.plone.org/job/pull-request-5.1/1348/
- [x] https://github.com/plone/plone.app.layout/pull/115

# More complex PRs, tested extra:
These PRs might need content upgrade, as they remove modules, which other persistant object might have relied upon.
- [ ] https://github.com/plone/plone.app.blob/pull/37
- [ ] https://github.com/plone/Products.ATContentTypes/pull/42

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Some of the Jenkins jobs failed with this message:

"mr.developer: The package 'Products.LinguaPlone' from auto-checkout has no source information."

That package is not mentioned anywhere in coredev 5.0 and 5.1, so I don't know why Jenkins decides it needs to check it out... Ah, I see you have added a LinguaPlone pull request in the jobs for 5.0 and 5.1, which would cause this.

I have restarted some jobs:

- 5.0: http://jenkins.plone.org/job/pull-request-5.0/1821/
- 5.1: http://jenkins.plone.org/job/pull-request-5.1/1352/

The 4.3 tests are passing. LinguaPlone is the only one in there that is only for 4.3. I will merge that one.

**Comment by mauritsvanrees** [comment]
The 5.0 tests are passing.

5.1 has an uninteresting failure, which I hope I fixed in [`contentmigration`](https://github.com/plone/Products.contentmigration/pull/13/commits/d4603fbcfb353dfa048e0b31851d79f2b21b9c75). Oh, I now see that a similar fix has already been done on master. Apparently the `thet-atifix` branch was based on an earlier version.
I have now rebased that branch.

**Comment by mauritsvanrees** [comment]
In fact, this means that all tests on 4.3, 5.0 and 5.1 pass. At least, I'm pretty sure that the single test failure for contentmigration on 5.1, which was already fixed on master, will go away.
I will merge all pull requests, except for the two under "More complex PRs, tested extra" in the description.

**Comment by mauritsvanrees** [comment]
I have merged all. That should keep Jenkins busy for a while. :-)

**Comment by mauritsvanrees** [comment]
After all the merges, Jenkins is still happy.

**Comment by thet** [comment]
@mauritsvanrees tnx for all the merges!
I started a 5.0 and 5.1 jenkins job for https://github.com/plone/plone.app.blob/pull/37 - maybe there are no upgrade steps needed, as long as we do not merge this ATContentTypes PR, which removes the deprecated imports.

**Comment by thet** [comment]
1) the interface.py should probably not be removed due to BBB compatibility.
2) this is outdated, I'll close it.

**Comment by thet** [comment]
1) the interface.py should probably not be removed due to BBB compatibility.
2) this is outdated, I'll close it.

**Pull request closed without merging**
