### PR TITLE
hide atcontenttypes from installable products

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by vangheem** [comment]
tests running: http://jenkins.plone.org/job/pull-request-5.0/62/

**Comment by jensens** [comment]
hmm, i dont thing renaming ``default`` to ``install`` is a good idea. Also there are plenty test failures. 
Hiding can and should be done adding a utility implementing ``Products.CMFPlone.interfaces.INonInstallable``.

**Comment by vangheem** [comment]
We tried this. INonInstallable means that even the quick_installer tool can't install it which breaks other tests.

**Comment by jensens** [comment]
Can we keep ``default`` and set it to non-installable, and additionally add ``install``? Would this solve it? I know at least 2 customer projects of mine that would fail without ``default`` profile, because they depend on it in ``metadata.xml``.

**Comment by vangheem** [comment]
I tried that way. As far as I can tell, if you do that, then you can no install the product like you normally can. NonInstallable is not just a UI config, it's a hard config on quickinstaller.

**Comment by jensens** [comment]
@vangheem may we close this? I dont think the renaming is a good idea (see above) and I dont see an alternative.

**Pull request closed without merging**
